### ISSUE TITLE
PERSON: Mitgliederausweis & Paddlepass verlinken.

### ISSUE THREAD

**Issue by chrusu** [hitobito/hitobito_skv#26]
@chrusu commented on [Tue Jan 04 2022](https://github.com/hitobito/hitobito/issues/1576)

![image](https://user-images.githubusercontent.com/17568539/148069049-99966738-f7ab-476b-9081-5bda089ab804.png)

ACHTUNG: "Anzeigen" statt "Download" (Linktext)

# Tech-Spec
- https://github.com/hitobito/hitobito/tree/master/app/views/people

# ToDo
- [ ] Neue Sektion Dokumente erstellen in SKV Wagon
- [ ] Link aus Export Dropdown entfernen
- [ ] Link zur Anzeige des Mitgliederausweises
- [ ] Link zur Anzeige des Paddle Ausweises
