### ISSUE TITLE
PEOPLE: Qualifikationen erfassen

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_skv#40]
Als Mitarbeiterin des SKV möchte ich, dass ich den Personen, auf welchen ich Schreibrechte habe, Qualifikation über den Erstellen-Button unten rechts hinzufügen kann. (Analog Bruno Schmid vom SVSE)
Hierfür wurde bereits die Gruppe "Mitarbeitende" für die Erstellung von Kursen freigegeben.
Dies funktioniert so aber nicht, da die Berechtigungsabfrage bei Ability nur den Layer berücksichtigt, auf welchem die Kurse aktiviert wurden.

Neu soll der Layer Schweizerischer Kanu-Verband für Event-Kurse aktiviert werden.

# Mockup
![Screenshot from 2022-10-14 16-45-12](https://user-images.githubusercontent.com/69250571/195875551-f33aa13c-0ba0-47fd-a871-c9d2926add19.png)

# Tech-Spec

- Qualifikation über den Erstellen-Button hinzufügbar machen 
- Berechtigungsabfrage Ability berücksichtigt Layer und keine Gruppen 
- Layer Schweizerischer Kanu-Verband für Event-Kurse aktivieren

# ToDo

- [ ] Layer Schweizerischer Kanu-Verband für Event-Kurse aktivieren
- [ ] Sicherstellen dass Erstellen-Button verfügbar ist
- [ ] Mit angemessener Rolle "durchklicken"
- [ ] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen
