### ISSUE TITLE
GROUPS: Rollen anpassen

### ISSUE THREAD

**Issue by mlue00** [hitobito/hitobito_skv#42]
Als Mitarbeiter:in des SKV möchte ich, dass einige Rollenberechtigungen angepasst werden, damit diese besser zum Tätigkeitsbereich der Mitglieder passen.

Neu sollen die folgenden Rollen angepasst werden:

- [ ] Schweizerischer Kanu-Verband > Vorstand > Präsident*in: [:layer_and_below_read]
- [ ] Schweizerischer Kanu-Verband > Vorstand > Finanzchef*in: [:layer_and_below_read, :finance]
- [ ] Schweizerischer Kanu-Verband > Vorstand > Vorstandsmitglied: [:layer_and_below_read]
- [ ] Schweizerischer Kanu-Verband > Geschäftsleitung > Mitarbeitende*r: > [:layer_and_below_full, :admin] 
- [ ] Schweizerischer Kanu-Verband > Mitarbeitende > Trainer*in: [:group_read]
- [ ]  Schweizerischer Kanu-Verband > Mitglieder > Mitglied: []
- [ ] Global > Sektion > Vorstand > Präsident:in [::layer_and_below_full]
- [ ] Global > Sektion > Vorstand > Kassier:in [:layer_and_below_full, :finance]
- [ ] Global > Sektion > Vorstand > Sekretär:in [:layer_and_below_full]
- [ ] Global > Sektion > Vorstand > Vorstandsmitglied [:layer_and_below_full]
- [ ] Global > Sektion > Finanzchef*in: Rolle soll gelöscht werden

# Tech-Spec

- Die Anpassungen beziehen sich auf die aktuelle Struktur welche im README.md des SKV abgebildet ist.

# ToDo

- [ ] Die aufgelisteten Rollen sind angepasst
- [ ] Specs schreiben
- [ ] Mit angemessener Rolle "durchklicken"
