### ISSUE TITLE
GROUPS: Neue Rolle "Anschlussmitglied"

### ISSUE THREAD

**Issue by ThomasEllenberger** [hitobito/hitobito_skv#51]
Eine Person kann beim SKV Mitglied in verschiedenen Sektionen sein. Verrechnet wird ihm der Mitgliederbeitrag jedoch immer nur in der Hauptsektion.
Bisher wurde mit Tags gearbeitet um die Hauptmitgliedschaft und Anschlussmitgliedschaften auseinander halten zu können.
Zukünftig soll dies mit einer neuen Rolle "Anschlussmitgliedschaft" Auf der Ebene Sektion gelöst werden.
Ein Anschlussmitglied soll die gleichen Berechtigungen haben, wie ein Mitglied auf der gleichen Ebene.

# Mockup

![Image](https://github.com/hitobito/hitobito_skv/assets/100761305/a0998cae-6ce0-42fa-861e-70cf29cc97e5)

# ToDo

- [x] Rolle Sektion/Anschlussmitgliedschaft hinzufügen
- [x] ~Permission `:group_read` vergeben~ das README und der Screenshot waren veraltet
- [x] README aktualisieren, um neue Rollenstruktur dort aufzunehmen
- [x] CHANGELOG-Eintrag unter "unreleased" unten hinzufügen

## weiteres

- [x] Neue Rolle in locales aufnehmen
